queues.stomp:
  pattern: "stomp://{host}/{queue}"
  defaults:
    _connector: @smartesb.connectors.queue
    queue_driver: @smartesb.default_queue_driver
    prefix: "%kernel.environment%/fv_%flows.version%"
  requirements:
    queue: "[a-zA-Z0-9/]+"

queues.generic:
  pattern: "queue://{host}/{queue}"
  defaults:
    _connector: @smartesb.connectors.queue
    queue_driver: @smartesb.default_queue_driver
    prefix: "%kernel.environment%/fv_%flows.version%"
  requirements:
    queue: "[a-zA-Z0-9/]+"

direct:
  pattern: "direct://{host}/{subroutine}"
  defaults:
    _connector: @smartesb.connector.direct