parameters:
  smartesb.definitions.router.class: Smartbox\Integration\CamelConfigBundle\ProcessorDefinitions\RouterDefinition
  smartesb.definitions.multicast.class: Smartbox\Integration\CamelConfigBundle\ProcessorDefinitions\MulticastDefinition
  smartesb.definitions.pipeline.class: Smartbox\Integration\CamelConfigBundle\ProcessorDefinitions\PipelineDefinition
  smartesb.definitions.transformer.class: Smartbox\Integration\CamelConfigBundle\ProcessorDefinitions\TransformerDefinition
  smartesb.definitions.throw_exception.class: Smartbox\Integration\CamelConfigBundle\ProcessorDefinitions\ThrowExceptionDefinition

services:
  smartesb.definitions.router:
      class: %smartesb.definitions.router.class%
      tags:
        - { name: smartesb.definitions.choice }
      calls:
        - [setEvaluator, [@smartesb.util.evaluator]]
        - [setProcessorClass, [%smartesb.processor.router.class%]]

  smartesb.definitions.multicast:
        class: %smartesb.definitions.multicast.class%
        tags:
          - { name: smartesb.definitions.multicast }
        calls:
          - [setProcessorClass, [%smartesb.processor.multicast.class%]]

  smartesb.definitions.pipeline:
      class: %smartesb.definitions.pipeline.class%
      tags:
        - { name: smartesb.definitions.pipeline }
      calls:
        - [setProcessorClass, [%smartesb.processor.pipeline.class%]]

  smartesb.definitions.transformer:
      class: %smartesb.definitions.transformer.class%
      tags:
        - { name: smartesb.definitions.transform }
      calls:
        - [setEvaluator, [@smartesb.util.evaluator]]
        - [setProcessorClass, [%smartesb.processor.transformer.class%]]

  smartesb.definitions.throw_exception:
      class: %smartesb.definitions.throw_exception.class%
      tags:
        - { name: smartesb.definitions.throwException }
      calls:
        - [setProcessorClass, [%smartesb.processor.throw_exception.class%]]