language: php

php:
  - 7.0

env:
  - SYMFONY_VERSION=2.7.*

before_script:
  - if [[ "$(php -v | grep 'PHP 7')" ]]; then yes | pecl install -f apcu; composer require atoum/atoum; fi
  - composer self-update
  - composer install

script:
  - bin/phpunit --coverage-text --debug

notifications:
  email: true
