language: php

php:
  - 7.0

env:
  - SYMFONY_VERSION=2.7.*

before_script:
  - composer self-update
#  - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update
  - composer update --no-interaction --prefer-source

script:
  - phpunit --coverage-text

notifications:
  email: true
